Create Community Brainstorming
HydroBlockchain/hcdp pull request #216
Opened 2018-08-08 14:12 UTC by milvinae

2018-08-08 19:01 UTC, AnuragHydro requested changes
Can you put this one folder out? so it would be /hcdp/community-brainstorming rather than /hcdp/.github/ISSUE_TEMPLATE/Community Brainstorming? It should be within the HCDP folder, but not within the issues folder.

2018-08-08 19:38 UTC, milvinae commented
OK, you should have that now. Deleted the original commit so let me know if there are any issues.

Once its up I'll complete the tutorial.

2018-08-08 19:45 UTC, AnuragHydro approved these changes

2018-08-08 19:49 UTC, merged

2018-08-09 12:16 UTC, milvinae commented
If the Issues tab doesn't work then Projects gives you the kanban board as Mike suggested. The issue with that is I think that the Community would have to do pull requests to comment which defeats the object of it and increases workload.

Otherwise there could be a separate Hydro Community GitHub for discussion, with only viable ideas getting sent over to the official page, which might make things easier for you but has the problem of yet another place to check and further fragmentation.